feeds:
  - name: All
    url: https://www.reddit.com/r/all/.json

  - name: reddit.com (time capsule)
    url: https://www.reddit.com/r/reddit.com/.json

  - name: Python
    url: https://www.reddit.com/r/python/.json

  - name: Linux
    url: https://www.reddit.com/r/linux/.json

  - name: Programming
    url: https://www.reddit.com/r/programming/.json

theme: default